package com.endra.spell
import android.os.Bundle
import android.speech.tts.TextToSpeech
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import java.util.Locale
private val Navy=Color(0xFF061A12); private val Card=Color(0xFF0D2B1D); private val Gold=Color(0xFF8BC34A); private val Cream=Color(0xFFFFF4D6)
class MainActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{MaterialTheme{EndraSpellApp()}}}}
@Composable fun EndraSpellApp(){var screen by remember{mutableStateOf("home")};var child by remember{mutableStateOf("James")};val context=LocalContext.current;var tts by remember{mutableStateOf<TextToSpeech?>(null)}
 DisposableEffect(Unit){val engine=TextToSpeech(context){if(it==TextToSpeech.SUCCESS)tts?.language=Locale.US};tts=engine;onDispose{engine.shutdown()}}
 Surface(Modifier.fillMaxSize(),color=Navy){when(screen){"home"->Home(child,{child=it},{screen="dashboard"});"dashboard"->Dashboard(child,{screen=it},{screen="home"});"words"->Words{screen="dashboard"};"games"->Games({screen="dashboard"},{screen=it});"type"->TypeGame(tts){screen="games"};"quiz"->Quiz(tts){screen="dashboard"};"progress"->Progress{screen="dashboard"};else->Dashboard(child,{screen=it},{screen="home"})}}}
@Composable fun Header(title:String,back:(()->Unit)?=null){Row(Modifier.fillMaxWidth().padding(20.dp),verticalAlignment=Alignment.CenterVertically){if(back!=null)TextButton(onClick=back){Text("‹ Back",color=Gold)};Text(title,color=Cream,fontSize=26.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(start=8.dp))}}
@Composable fun GoldButton(text:String,onClick:()->Unit){Button(onClick=onClick,modifier=Modifier.fillMaxWidth().height(58.dp).padding(vertical=4.dp),colors=ButtonDefaults.buttonColors(containerColor=Gold,contentColor=Navy),shape=RoundedCornerShape(18.dp)){Text(text,fontWeight=FontWeight.Bold,fontSize=17.sp)}}
@Composable fun DarkButton(text:String,onClick:()->Unit){OutlinedButton(onClick=onClick,modifier=Modifier.fillMaxWidth().height(58.dp).padding(vertical=4.dp),shape=RoundedCornerShape(18.dp)){Text(text,color=Cream,fontSize=16.sp)}}
@Composable fun Home(child:String,choose:(String)->Unit,start:()->Unit){Column(Modifier.fillMaxSize().padding(28.dp).verticalScroll(rememberScrollState()),horizontalAlignment=Alignment.CenterHorizontally){Spacer(Modifier.height(24.dp));Text("✦",color=Gold,fontSize=48.sp);Text("EndraSpell",color=Gold,fontSize=40.sp,fontWeight=FontWeight.ExtraBold);Text("Build your spelling magic",color=Cream,fontSize=17.sp);Spacer(Modifier.height(36.dp));Text("Who's practicing?",color=Cream,fontSize=22.sp,fontWeight=FontWeight.Bold);listOf("James","Easton","Aiden").forEach{name->Button(onClick={choose(name)},modifier=Modifier.fillMaxWidth().padding(6.dp),colors=ButtonDefaults.buttonColors(containerColor=if(child==name)Gold else Card,contentColor=if(child==name)Navy else Cream),shape=RoundedCornerShape(20.dp)){Text(name,fontSize=20.sp)}};Spacer(Modifier.height(18.dp));GoldButton("Start with $child",start)}}
@Composable fun Dashboard(child:String,go:(String)->Unit,back:()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(18.dp)){Header("Hi, $child! ✨",back);Text("What would you like to practice?",color=Cream,fontSize=18.sp,modifier=Modifier.padding(8.dp));GoldButton("📚  My Words"){go("words")};DarkButton("🎮  Practice Games"){go("games")};DarkButton("🔊  Practice Quiz"){go("quiz")};DarkButton("🏆  My Progress"){go("progress")};Spacer(Modifier.height(22.dp));androidx.compose.material3.Card(colors=CardDefaults.cardColors(containerColor=Card),shape=RoundedCornerShape(22.dp),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(20.dp)){Text("This Week",color=Gold,fontWeight=FontWeight.Bold,fontSize=20.sp);Text("10 spelling words • 5 Heart Words",color=Cream,modifier=Modifier.padding(top=8.dp));Text("Tip: practice a little every day!",color=Cream.copy(alpha=.8f),modifier=Modifier.padding(top=10.dp))}}}}
@Composable fun Words(back:()->Unit){val sample=listOf("beautiful","because","different","favorite","important","people","school","thought","through","together");Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(18.dp)){Header("My Words",back);Text("This Week's Spelling Words",color=Gold,fontSize=20.sp,fontWeight=FontWeight.Bold);sample.forEachIndexed{i,w->Text((i+1).toString()+".  "+w,color=Cream,fontSize=18.sp,modifier=Modifier.padding(7.dp))};Spacer(Modifier.height(16.dp));Text("❤️ Heart Words",color=Gold,fontSize=20.sp,fontWeight=FontWeight.Bold);Text("the   said   was   have   what",color=Cream,fontSize=18.sp,modifier=Modifier.padding(10.dp));DarkButton("Previous Lists"){};GoldButton("+ Add / Edit Words"){}}}
@Composable fun Games(back:()->Unit,go:(String)->Unit){Column(Modifier.fillMaxSize().padding(18.dp).verticalScroll(rememberScrollState())){Header("Practice Games",back);GoldButton("⌨️  Type the Word"){go("type")};DarkButton("🔎  Spot the Right Word"){};DarkButton("🔀  Word Scramble"){};DarkButton("🧩  Missing Letters"){};DarkButton("🔤  Word Search"){}}}
@Composable fun TypeGame(tts:TextToSpeech?,back:()->Unit){var answer by remember{mutableStateOf("")};var msg by remember{mutableStateOf("")};val word="beautiful";Column(Modifier.fillMaxSize().padding(20.dp),horizontalAlignment=Alignment.CenterHorizontally){Header("Type the Word",back);Spacer(Modifier.height(30.dp));Text("🔊",fontSize=70.sp);GoldButton("Hear the Word"){tts?.speak(word,TextToSpeech.QUEUE_FLUSH,null,"word")};Spacer(Modifier.height(18.dp));OutlinedTextField(answer,{answer=it},label={Text("Type what you hear")},modifier=Modifier.fillMaxWidth(),singleLine=true,colors=OutlinedTextFieldDefaults.colors(focusedTextColor=Cream,unfocusedTextColor=Cream,focusedBorderColor=Gold,unfocusedBorderColor=Cream));GoldButton("Check"){msg=if(answer.trim().equals(word,true))"✨ Correct!" else "Try again — listen closely."};Text(msg,color=Gold,fontSize=20.sp,modifier=Modifier.padding(18.dp))}}
@Composable fun Quiz(tts:TextToSpeech?,back:()->Unit){val words=listOf("beautiful","because","different","favorite","important");var index by remember{mutableIntStateOf(0)};var answer by remember{mutableStateOf("")};var correct by remember{mutableIntStateOf(0)};var done by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize().padding(20.dp),horizontalAlignment=Alignment.CenterHorizontally){Header("Practice Quiz",back);if(!done){Text("Word "+(index+1)+" of "+words.size,color=Cream,fontSize=18.sp);Spacer(Modifier.height(24.dp));GoldButton("🔊 Hear Word"){tts?.speak(words[index],TextToSpeech.QUEUE_FLUSH,null,"quiz")};OutlinedTextField(answer,{answer=it},label={Text("Spell the word")},modifier=Modifier.fillMaxWidth().padding(vertical=18.dp),singleLine=true,colors=OutlinedTextFieldDefaults.colors(focusedTextColor=Cream,unfocusedTextColor=Cream,focusedBorderColor=Gold,unfocusedBorderColor=Cream));GoldButton("Submit"){if(answer.trim().equals(words[index],true))correct++;answer="";if(index==words.lastIndex)done=true else index++}}else{Spacer(Modifier.height(60.dp));Text("Quiz Complete! ⭐",color=Gold,fontSize=30.sp,fontWeight=FontWeight.Bold);Text("$correct / "+words.size,color=Cream,fontSize=44.sp,modifier=Modifier.padding(24.dp));GoldButton("Done",back)}}}
@Composable fun Progress(back:()->Unit){Column(Modifier.fillMaxSize().padding(18.dp).verticalScroll(rememberScrollState())){Header("My Progress",back);Text("⭐ Words Mastered",color=Gold,fontSize=22.sp,fontWeight=FontWeight.Bold);Text("0 — let's start practicing!",color=Cream,fontSize=18.sp,modifier=Modifier.padding(12.dp));Text("Recent Quiz Scores",color=Gold,fontSize=22.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=24.dp));Text("Your scores will appear here after you take a quiz.",color=Cream,modifier=Modifier.padding(12.dp));Text("Needs More Practice",color=Gold,fontSize=22.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=24.dp));Text("Mistakes will be saved here so you can learn from them.",color=Cream,modifier=Modifier.padding(12.dp))}}
