package com.endra.spell
import android.os.Bundle
import android.speech.tts.TextToSpeech
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.Image
import androidx.compose.foundation.shape.CutCornerShape
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.layout.ContentScale
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import java.util.Locale
private val Navy=Color(0xFF020D08); private val Forest=Color(0xFF06331D); private val Card=Color(0xFF082B1B); private val Gold=Color(0xFFE7C65B); private val Leaf=Color(0xFF5EA83F); private val Cream=Color(0xFFFFF0C2); private val Parchment=Color(0xFFF3DFA7)
class MainActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{MaterialTheme{EndraSpellApp()}}}}
@Composable fun EndraSpellApp(){var screen by remember{mutableStateOf("home")};var child by remember{mutableStateOf("James")};var spellingWords by remember{mutableStateOf(listOf("beautiful","because","different","favorite","important","people","school","thought","through","together"))};var heartWords by remember{mutableStateOf(listOf("the","said","was","have","what"))};val context=LocalContext.current;var tts by remember{mutableStateOf<TextToSpeech?>(null)}
 DisposableEffect(Unit){val engine=TextToSpeech(context){if(it==TextToSpeech.SUCCESS)tts?.language=Locale.US};engine.setSpeechRate(0.72f);tts=engine;onDispose{engine.shutdown()}}
 EnchantedFrame{when(screen){"home"->Home(child,{child=it},{screen="dashboard"});"dashboard"->Dashboard(child,{screen=it},{screen="home"});"words"->Words(spellingWords,heartWords,{spellingWords=it},{heartWords=it}){screen="dashboard"};"games"->Games({screen="dashboard"},{screen=it});"type"->TypeGame(tts){screen="games"};"quiz"->Quiz(tts){screen="dashboard"};"progress"->Progress{screen="dashboard"};else->Dashboard(child,{screen=it},{screen="home"})}}}
@Composable fun EnchantedFrame(content:@Composable BoxScope.()->Unit){Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Color(0xFF03150B),Color(0xFF06331D),Color(0xFF010A06))))){Canvas(Modifier.fillMaxSize()){val w=size.width;val h=size.height;for(i in 0..18){val x=w*((i*37%91)+5)/100f;val y=h*((i*61%89)+5)/100f;drawCircle(Gold.copy(alpha=.30f),2f+(i%3),Offset(x,y))};drawLine(Gold.copy(alpha=.9f),Offset(8f,8f),Offset(w-8f,8f),3f);drawLine(Gold.copy(alpha=.9f),Offset(8f,h-8f),Offset(w-8f,h-8f),3f);drawLine(Gold.copy(alpha=.65f),Offset(8f,8f),Offset(8f,h-8f),2f);drawLine(Gold.copy(alpha=.65f),Offset(w-8f,8f),Offset(w-8f,h-8f),2f)};Box(Modifier.fillMaxSize().padding(horizontal=12.dp)){content()}}}
@Composable fun CastleHeader(){Box(Modifier.fillMaxWidth().height(230.dp)){Canvas(Modifier.fillMaxSize()){val w=size.width;val h=size.height;val moon=Color(0xFFD7F59A);drawCircle(moon.copy(alpha=.20f),w*.17f,Offset(w*.72f,h*.27f));for(i in 0..13){drawCircle(Gold.copy(alpha=.45f),2f+(i%2),Offset(w*((i*31%83)+8)/100f,h*((i*47%45)+5)/100f))};val tree=Color(0xFF04170C);drawCircle(tree,w*.20f,Offset(w*.08f,h*.30f));drawCircle(tree,w*.18f,Offset(w*.92f,h*.27f));drawCircle(Color(0xFF0A3B21),w*.12f,Offset(w*.18f,h*.37f));drawCircle(Color(0xFF0A3B21),w*.12f,Offset(w*.82f,h*.38f));val base=h*.69f;val castle=Color(0xFF03170D);fun spire(cx:Float,tw:Float,th:Float){drawRect(castle,Offset(cx-tw/2,base-th),Size(tw,th));val top=base-th;val path=androidx.compose.ui.graphics.Path().apply{moveTo(cx-tw*.68f,top);lineTo(cx,top-tw*1.15f);lineTo(cx+tw*.68f,top);close()};drawPath(path,castle);drawLine(Gold.copy(alpha=.50f),Offset(cx-tw*.68f,top),Offset(cx,top-tw*1.15f),2f);drawLine(Gold.copy(alpha=.50f),Offset(cx,top-tw*1.15f),Offset(cx+tw*.68f,top),2f);drawCircle(Gold.copy(alpha=.8f),2.5f,Offset(cx,top+th*.35f))};spire(w*.31f,w*.065f,h*.27f);spire(w*.43f,w*.075f,h*.36f);spire(w*.54f,w*.095f,h*.46f);spire(w*.65f,w*.07f,h*.32f);spire(w*.74f,w*.06f,h*.24f);drawRect(castle,Offset(w*.25f,base-h*.13f),Size(w*.55f,h*.13f));drawLine(Gold.copy(alpha=.65f),Offset(w*.20f,base+2),Offset(w*.84f,base+2),3f);for(i in 0..7){val x=w*(.29f+i*.064f);drawCircle(Gold.copy(alpha=.65f),2.5f,Offset(x,base-h*.08f))};drawLine(Leaf.copy(alpha=.8f),Offset(0f,h*.77f),Offset(w,h*.77f),5f)};Column(Modifier.fillMaxSize(),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Bottom){Text("EndraSpell",color=Gold,fontSize=43.sp,fontWeight=FontWeight.ExtraBold);Text("Where words grow into magic",color=Cream,fontSize=15.sp);Text("❧  Enchanted Forest Academy  ❧",color=Gold,fontSize=14.sp);Spacer(Modifier.height(8.dp))}}}
@Composable fun MagicBook(){Column(horizontalAlignment=Alignment.CenterHorizontally){Text("✨  ✦  ✨",color=Gold,fontSize=20.sp);Text("📖",fontSize=58.sp);Text("❧  ✧  ❧",color=Gold,fontSize=20.sp)}}
@Composable fun ParchmentPanel(content:@Composable ColumnScope.()->Unit){androidx.compose.material3.Card(colors=CardDefaults.cardColors(containerColor=Parchment),shape=CutCornerShape(10.dp),modifier=Modifier.fillMaxWidth().border(2.dp,Gold,CutCornerShape(10.dp))){Column(Modifier.padding(18.dp),content=content)}}
@Composable fun Header(title:String,back:(()->Unit)?=null){Row(Modifier.fillMaxWidth().padding(20.dp),verticalAlignment=Alignment.CenterVertically){if(back!=null)TextButton(onClick=back){Text("‹ Back",color=Gold)};Text("❧  $title  ❧",color=Gold,fontSize=26.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(start=8.dp))}}
@Composable fun GoldButton(text:String,onClick:()->Unit){Button(onClick=onClick,modifier=Modifier.fillMaxWidth().height(58.dp).padding(vertical=4.dp),colors=ButtonDefaults.buttonColors(containerColor=Gold,contentColor=Navy),shape=CutCornerShape(10.dp),border=androidx.compose.foundation.BorderStroke(2.dp,Gold)){Text("✦  $text  ✦",fontWeight=FontWeight.Bold,fontSize=17.sp)}}
@Composable fun DarkButton(text:String,onClick:()->Unit){OutlinedButton(onClick=onClick,modifier=Modifier.fillMaxWidth().height(58.dp).padding(vertical=4.dp),shape=CutCornerShape(10.dp),colors=ButtonDefaults.outlinedButtonColors(containerColor=Card),border=androidx.compose.foundation.BorderStroke(1.dp,Gold.copy(alpha=.8f))){Text("🍃  $text",color=Cream,fontSize=16.sp)}}
@Composable fun Home(child:String,choose:(String)->Unit,start:()->Unit){Column(Modifier.fillMaxSize().padding(horizontal=14.dp).verticalScroll(rememberScrollState()),horizontalAlignment=Alignment.CenterHorizontally){CastleHeader();Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){HomeTile("📖","Practice\nWords",Modifier.weight(1f)){start()};HomeTile("💛","Heart\nWords",Modifier.weight(1f)){start()}};Spacer(Modifier.height(10.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){HomeTile("📝","Add / Edit\nWords",Modifier.weight(1f)){start()};HomeTile("📊","Progress",Modifier.weight(1f)){start()}};Spacer(Modifier.height(12.dp));Text("✨   📖   ✨",fontSize=34.sp,color=Gold);Text("Choose your learner",color=Gold,fontSize=19.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(6.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){listOf("James","Easton","Aiden").forEach{name->OutlinedButton(onClick={choose(name)},modifier=Modifier.weight(1f),colors=ButtonDefaults.outlinedButtonColors(containerColor=if(child==name)Gold else Color(0xFF052A18)),border=androidx.compose.foundation.BorderStroke(1.5.dp,Gold)){Text(name,color=if(child==name)Navy else Cream)}}};Spacer(Modifier.height(8.dp));GoldButton("Enter the Forest",start);Spacer(Modifier.height(18.dp))}}
@Composable fun HomeTile(icon:String,label:String,modifier:Modifier=Modifier,onClick:()->Unit){Card(onClick=onClick,modifier=modifier.height(150.dp).border(2.dp,Gold,CutCornerShape(12.dp)),shape=CutCornerShape(12.dp),colors=CardDefaults.cardColors(containerColor=Card)){Column(Modifier.fillMaxSize().padding(12.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text(icon,fontSize=38.sp);Text(label,color=Cream,fontSize=18.sp,fontWeight=FontWeight.Bold)}}}
@Composable fun Dashboard(child:String,go:(String)->Unit,back:()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(18.dp)){Header("Hi, $child! ✨",back);Text("What would you like to practice?",color=Cream,fontSize=18.sp,modifier=Modifier.padding(8.dp));GoldButton("📚  My Words"){go("words")};DarkButton("🎮  Practice Games"){go("games")};DarkButton("🔊  Practice Quiz"){go("quiz")};DarkButton("🏆  My Progress"){go("progress")};Spacer(Modifier.height(22.dp));androidx.compose.material3.Card(colors=CardDefaults.cardColors(containerColor=Card),shape=RoundedCornerShape(22.dp),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(20.dp)){Text("This Week",color=Gold,fontWeight=FontWeight.Bold,fontSize=20.sp);Text("10 spelling words • 5 Heart Words",color=Cream,modifier=Modifier.padding(top=8.dp));Text("Tip: practice a little every day!",color=Cream.copy(alpha=.8f),modifier=Modifier.padding(top=10.dp))}}}}
@Composable fun Words(spelling:List<String>,heart:List<String>,setSpelling:(List<String>)->Unit,setHeart:(List<String>)->Unit,back:()->Unit){var editing by remember{mutableStateOf(false)};var weeklyText by remember(spelling){mutableStateOf(spelling.joinToString("\n"))};var heartText by remember(heart){mutableStateOf(heart.joinToString("\n"))};Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(18.dp)){Header("🌿 My Words",back);if(editing){Text("Weekly Spelling Words",color=Gold,fontSize=20.sp,fontWeight=FontWeight.Bold);OutlinedTextField(weeklyText,{weeklyText=it},modifier=Modifier.fillMaxWidth().height(220.dp),label={Text("One word per line")},colors=OutlinedTextFieldDefaults.colors(focusedTextColor=Cream,unfocusedTextColor=Cream,focusedBorderColor=Gold,unfocusedBorderColor=Cream));Spacer(Modifier.height(16.dp));Text("❤️ Heart Words",color=Gold,fontSize=20.sp,fontWeight=FontWeight.Bold);OutlinedTextField(heartText,{heartText=it},modifier=Modifier.fillMaxWidth().height(180.dp),label={Text("Add Heart Words — one per line")},colors=OutlinedTextFieldDefaults.colors(focusedTextColor=Cream,unfocusedTextColor=Cream,focusedBorderColor=Gold,unfocusedBorderColor=Cream));GoldButton("Save Words"){setSpelling(weeklyText.lines().map{it.trim()}.filter{it.isNotEmpty()}.distinct());setHeart(heartText.lines().map{it.trim()}.filter{it.isNotEmpty()}.distinct());editing=false};DarkButton("Cancel"){editing=false}}else{Text("This Week's Spelling Words",color=Gold,fontSize=20.sp,fontWeight=FontWeight.Bold);spelling.forEachIndexed{i,w->Text("${i+1}.  $w",color=Cream,fontSize=18.sp,modifier=Modifier.padding(7.dp))};Spacer(Modifier.height(16.dp));Text("❤️ Heart Words",color=Gold,fontSize=20.sp,fontWeight=FontWeight.Bold);Text(heart.joinToString("   "),color=Cream,fontSize=18.sp,modifier=Modifier.padding(10.dp));DarkButton("Previous Lists"){};GoldButton("+ Add / Edit Words"){editing=true}}}}
@Composable fun Games(back:()->Unit,go:(String)->Unit){Column(Modifier.fillMaxSize().padding(18.dp).verticalScroll(rememberScrollState())){Header("🍃 Practice Games",back);GoldButton("⌨️  Type the Word"){go("type")};DarkButton("🔎  Spot the Right Word"){};DarkButton("🔀  Word Scramble"){};DarkButton("🧩  Missing Letters"){};DarkButton("🔤  Word Search"){}}}
@Composable fun TypeGame(tts:TextToSpeech?,back:()->Unit){var answer by remember{mutableStateOf("")};var msg by remember{mutableStateOf("")};val word="beautiful";Column(Modifier.fillMaxSize().padding(20.dp),horizontalAlignment=Alignment.CenterHorizontally){Header("🌱 Type the Word",back);Spacer(Modifier.height(30.dp));Text("🔊",fontSize=70.sp);GoldButton("Hear the Word"){tts?.speak(word,TextToSpeech.QUEUE_FLUSH,null,"word")};Spacer(Modifier.height(18.dp));OutlinedTextField(answer,{answer=it},label={Text("Type what you hear")},modifier=Modifier.fillMaxWidth(),singleLine=true,colors=OutlinedTextFieldDefaults.colors(focusedTextColor=Cream,unfocusedTextColor=Cream,focusedBorderColor=Gold,unfocusedBorderColor=Cream));GoldButton("Check"){msg=if(answer.trim().equals(word,true))"✨ Correct!" else "Try again — listen closely."};Text(msg,color=Gold,fontSize=20.sp,modifier=Modifier.padding(18.dp))}}
@Composable fun Quiz(tts:TextToSpeech?,back:()->Unit){val words=listOf("beautiful","because","different","favorite","important");var index by remember{mutableIntStateOf(0)};var answer by remember{mutableStateOf("")};var correct by remember{mutableIntStateOf(0)};var done by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize().padding(20.dp),horizontalAlignment=Alignment.CenterHorizontally){Header("📖 Practice Quiz",back);if(!done){Text("Word "+(index+1)+" of "+words.size,color=Cream,fontSize=18.sp);Spacer(Modifier.height(24.dp));GoldButton("🔊 Hear Word"){tts?.speak(words[index],TextToSpeech.QUEUE_FLUSH,null,"quiz")};OutlinedTextField(answer,{answer=it},label={Text("Spell the word")},modifier=Modifier.fillMaxWidth().padding(vertical=18.dp),singleLine=true,colors=OutlinedTextFieldDefaults.colors(focusedTextColor=Cream,unfocusedTextColor=Cream,focusedBorderColor=Gold,unfocusedBorderColor=Cream));GoldButton("Submit"){if(answer.trim().equals(words[index],true))correct++;answer="";if(index==words.lastIndex)done=true else index++}}else{Spacer(Modifier.height(60.dp));Text("Quiz Complete! ⭐",color=Gold,fontSize=30.sp,fontWeight=FontWeight.Bold);Text("$correct / "+words.size,color=Cream,fontSize=44.sp,modifier=Modifier.padding(24.dp));GoldButton("Done",back)}}}
@Composable fun Progress(back:()->Unit){Column(Modifier.fillMaxSize().padding(18.dp).verticalScroll(rememberScrollState())){Header("🌳 My Progress",back);Text("⭐ Words Mastered",color=Gold,fontSize=22.sp,fontWeight=FontWeight.Bold);Text("0 — let's start practicing!",color=Cream,fontSize=18.sp,modifier=Modifier.padding(12.dp));Text("Recent Quiz Scores",color=Gold,fontSize=22.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=24.dp));Text("Your scores will appear here after you take a quiz.",color=Cream,modifier=Modifier.padding(12.dp));Text("Needs More Practice",color=Gold,fontSize=22.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=24.dp));Text("Mistakes will be saved here so you can learn from them.",color=Cream,modifier=Modifier.padding(12.dp))}}
