package com.endra.spell
import android.os.Bundle
import android.speech.tts.TextToSpeech
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.Image
import androidx.compose.foundation.shape.CutCornerShape
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.layout.ContentScale
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import java.util.Locale
private val Navy=Color(0xFF020D08); private val Forest=Color(0xFF06331D); private val Card=Color(0xFF082B1B); private val Gold=Color(0xFFE7C65B); private val Leaf=Color(0xFF5EA83F); private val Cream=Color(0xFFFFF0C2); private val Parchment=Color(0xFFF3DFA7)
class MainActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{MaterialTheme{EndraSpellApp()}}}}
@Composable fun EndraSpellApp(){var screen by remember{mutableStateOf("home")};var child by remember{mutableStateOf("James")};var spellingWords by remember{mutableStateOf(listOf("beautiful","because","different","favorite","important","people","school","thought","through","together"))};var heartWords by remember{mutableStateOf(listOf("the","said","was","have","what"))};val context=LocalContext.current;var tts by remember{mutableStateOf<TextToSpeech?>(null)}
 DisposableEffect(Unit){val engine=TextToSpeech(context){if(it==TextToSpeech.SUCCESS)tts?.language=Locale.US};engine.setSpeechRate(0.72f);tts=engine;onDispose{engine.shutdown()}}
 EnchantedFrame{when(screen){"home"->Home(child,{child=it},{screen="dashboard"});"dashboard"->Dashboard(child,{screen=it},{screen="home"});"words"->Words(spellingWords,heartWords,{spellingWords=it},{heartWords=it}){screen="dashboard"};"games"->Games({screen="dashboard"},{screen=it});"type"->TypeGame(tts){screen="games"};"quiz"->Quiz(tts){screen="dashboard"};"progress"->Progress{screen="dashboard"};else->Dashboard(child,{screen=it},{screen="home"})}}}
@Composable fun EnchantedFrame(content:@Composable BoxScope.()->Unit){Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Color(0xFF010905),Color(0xFF032515),Navy)))){Canvas(Modifier.fillMaxSize()){val w=size.width;val h=size.height;for(i in 0..9){val x=w*((i*37%91)+5)/100f;val y=h*((i*61%89)+5)/100f;drawCircle(Gold.copy(alpha=.45f),3f+(i%3),Offset(x,y))};drawCircle(Leaf.copy(alpha=.20f),w*.42f,Offset(0f,h*.08f));drawCircle(Leaf.copy(alpha=.16f),w*.40f,Offset(w,h*.12f));drawLine(Gold.copy(alpha=.85f),Offset(10f,10f),Offset(w-10f,10f),3f);drawLine(Gold.copy(alpha=.85f),Offset(10f,h-10f),Offset(w-10f,h-10f),3f);drawLine(Gold.copy(alpha=.55f),Offset(10f,10f),Offset(10f,h-10f),2f);drawLine(Gold.copy(alpha=.55f),Offset(w-10f,10f),Offset(w-10f,h-10f),2f)};Column(Modifier.fillMaxSize()){Text("❧  🌿  ✦  🌿  ❧",color=Gold,fontSize=20.sp,modifier=Modifier.align(Alignment.CenterHorizontally).padding(top=12.dp));Box(Modifier.weight(1f).padding(horizontal=12.dp)){content()};Text("🌿  ✧  📖  ✧  🌿",color=Gold,fontSize=18.sp,modifier=Modifier.align(Alignment.CenterHorizontally).padding(bottom=10.dp))}}}
@Composable fun MagicBook(){Column(horizontalAlignment=Alignment.CenterHorizontally){Text("✨  ✦  ✨",color=Gold,fontSize=20.sp);Text("📖",fontSize=58.sp);Text("❧  ✧  ❧",color=Gold,fontSize=20.sp)}}
@Composable fun ParchmentPanel(content:@Composable ColumnScope.()->Unit){androidx.compose.material3.Card(colors=CardDefaults.cardColors(containerColor=Parchment),shape=CutCornerShape(10.dp),modifier=Modifier.fillMaxWidth().border(2.dp,Gold,CutCornerShape(10.dp))){Column(Modifier.padding(18.dp),content=content)}}
@Composable fun Header(title:String,back:(()->Unit)?=null){Row(Modifier.fillMaxWidth().padding(20.dp),verticalAlignment=Alignment.CenterVertically){if(back!=null)TextButton(onClick=back){Text("‹ Back",color=Gold)};Text("❧  $title  ❧",color=Gold,fontSize=26.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(start=8.dp))}}
@Composable fun GoldButton(text:String,onClick:()->Unit){Button(onClick=onClick,modifier=Modifier.fillMaxWidth().height(58.dp).padding(vertical=4.dp),colors=ButtonDefaults.buttonColors(containerColor=Gold,contentColor=Navy),shape=CutCornerShape(10.dp),border=androidx.compose.foundation.BorderStroke(2.dp,Gold)){Text("✦  $text  ✦",fontWeight=FontWeight.Bold,fontSize=17.sp)}}
@Composable fun DarkButton(text:String,onClick:()->Unit){OutlinedButton(onClick=onClick,modifier=Modifier.fillMaxWidth().height(58.dp).padding(vertical=4.dp),shape=CutCornerShape(10.dp),colors=ButtonDefaults.outlinedButtonColors(containerColor=Card),border=androidx.compose.foundation.BorderStroke(1.dp,Gold.copy(alpha=.8f))){Text("🍃  $text",color=Cream,fontSize=16.sp)}}
@Composable fun Home(child:String,choose:(String)->Unit,start:()->Unit){Column(Modifier.fillMaxSize().padding(28.dp).verticalScroll(rememberScrollState()),horizontalAlignment=Alignment.CenterHorizontally){Spacer(Modifier.height(24.dp));Image(painterResource(com.endra.spell.R.drawable.endra_launcher),null,modifier=Modifier.size(170.dp),contentScale=ContentScale.Fit);Text("EndraSpell",color=Gold,fontSize=42.sp,fontWeight=FontWeight.ExtraBold);Text("Where words grow into magic",color=Cream,fontSize=17.sp);MagicBook();Text("Enchanted Forest Academy",color=Gold,fontSize=14.sp,modifier=Modifier.padding(top=4.dp));Spacer(Modifier.height(36.dp));Text("Who's practicing?",color=Cream,fontSize=22.sp,fontWeight=FontWeight.Bold);listOf("James","Easton","Aiden").forEach{name->Button(onClick={choose(name)},modifier=Modifier.fillMaxWidth().padding(6.dp),colors=ButtonDefaults.buttonColors(containerColor=if(child==name)Gold else Card,contentColor=if(child==name)Navy else Cream),shape=RoundedCornerShape(20.dp)){Text(name,fontSize=20.sp)}};Spacer(Modifier.height(18.dp));GoldButton("Start with $child",start)}}
@Composable fun Dashboard(child:String,go:(String)->Unit,back:()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(18.dp)){Header("Hi, $child! ✨",back);Text("What would you like to practice?",color=Cream,fontSize=18.sp,modifier=Modifier.padding(8.dp));GoldButton("📚  My Words"){go("words")};DarkButton("🎮  Practice Games"){go("games")};DarkButton("🔊  Practice Quiz"){go("quiz")};DarkButton("🏆  My Progress"){go("progress")};Spacer(Modifier.height(22.dp));androidx.compose.material3.Card(colors=CardDefaults.cardColors(containerColor=Card),shape=RoundedCornerShape(22.dp),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(20.dp)){Text("This Week",color=Gold,fontWeight=FontWeight.Bold,fontSize=20.sp);Text("10 spelling words • 5 Heart Words",color=Cream,modifier=Modifier.padding(top=8.dp));Text("Tip: practice a little every day!",color=Cream.copy(alpha=.8f),modifier=Modifier.padding(top=10.dp))}}}}
@Composable fun Words(spelling:List<String>,heart:List<String>,setSpelling:(List<String>)->Unit,setHeart:(List<String>)->Unit,back:()->Unit){var editing by remember{mutableStateOf(false)};var weeklyText by remember(spelling){mutableStateOf(spelling.joinToString("\n"))};var heartText by remember(heart){mutableStateOf(heart.joinToString("\n"))};Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(18.dp)){Header("🌿 My Words",back);if(editing){Text("Weekly Spelling Words",color=Gold,fontSize=20.sp,fontWeight=FontWeight.Bold);OutlinedTextField(weeklyText,{weeklyText=it},modifier=Modifier.fillMaxWidth().height(220.dp),label={Text("One word per line")},colors=OutlinedTextFieldDefaults.colors(focusedTextColor=Cream,unfocusedTextColor=Cream,focusedBorderColor=Gold,unfocusedBorderColor=Cream));Spacer(Modifier.height(16.dp));Text("❤️ Heart Words",color=Gold,fontSize=20.sp,fontWeight=FontWeight.Bold);OutlinedTextField(heartText,{heartText=it},modifier=Modifier.fillMaxWidth().height(180.dp),label={Text("Add Heart Words — one per line")},colors=OutlinedTextFieldDefaults.colors(focusedTextColor=Cream,unfocusedTextColor=Cream,focusedBorderColor=Gold,unfocusedBorderColor=Cream));GoldButton("Save Words"){setSpelling(weeklyText.lines().map{it.trim()}.filter{it.isNotEmpty()}.distinct());setHeart(heartText.lines().map{it.trim()}.filter{it.isNotEmpty()}.distinct());editing=false};DarkButton("Cancel"){editing=false}}else{Text("This Week's Spelling Words",color=Gold,fontSize=20.sp,fontWeight=FontWeight.Bold);spelling.forEachIndexed{i,w->Text("${i+1}.  $w",color=Cream,fontSize=18.sp,modifier=Modifier.padding(7.dp))};Spacer(Modifier.height(16.dp));Text("❤️ Heart Words",color=Gold,fontSize=20.sp,fontWeight=FontWeight.Bold);Text(heart.joinToString("   "),color=Cream,fontSize=18.sp,modifier=Modifier.padding(10.dp));DarkButton("Previous Lists"){};GoldButton("+ Add / Edit Words"){editing=true}}}}
@Composable fun Games(back:()->Unit,go:(String)->Unit){Column(Modifier.fillMaxSize().padding(18.dp).verticalScroll(rememberScrollState())){Header("🍃 Practice Games",back);GoldButton("⌨️  Type the Word"){go("type")};DarkButton("🔎  Spot the Right Word"){};DarkButton("🔀  Word Scramble"){};DarkButton("🧩  Missing Letters"){};DarkButton("🔤  Word Search"){}}}
@Composable fun TypeGame(tts:TextToSpeech?,back:()->Unit){var answer by remember{mutableStateOf("")};var msg by remember{mutableStateOf("")};val word="beautiful";Column(Modifier.fillMaxSize().padding(20.dp),horizontalAlignment=Alignment.CenterHorizontally){Header("🌱 Type the Word",back);Spacer(Modifier.height(30.dp));Text("🔊",fontSize=70.sp);GoldButton("Hear the Word"){tts?.speak(word,TextToSpeech.QUEUE_FLUSH,null,"word")};Spacer(Modifier.height(18.dp));OutlinedTextField(answer,{answer=it},label={Text("Type what you hear")},modifier=Modifier.fillMaxWidth(),singleLine=true,colors=OutlinedTextFieldDefaults.colors(focusedTextColor=Cream,unfocusedTextColor=Cream,focusedBorderColor=Gold,unfocusedBorderColor=Cream));GoldButton("Check"){msg=if(answer.trim().equals(word,true))"✨ Correct!" else "Try again — listen closely."};Text(msg,color=Gold,fontSize=20.sp,modifier=Modifier.padding(18.dp))}}
@Composable fun Quiz(tts:TextToSpeech?,back:()->Unit){val words=listOf("beautiful","because","different","favorite","important");var index by remember{mutableIntStateOf(0)};var answer by remember{mutableStateOf("")};var correct by remember{mutableIntStateOf(0)};var done by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize().padding(20.dp),horizontalAlignment=Alignment.CenterHorizontally){Header("📖 Practice Quiz",back);if(!done){Text("Word "+(index+1)+" of "+words.size,color=Cream,fontSize=18.sp);Spacer(Modifier.height(24.dp));GoldButton("🔊 Hear Word"){tts?.speak(words[index],TextToSpeech.QUEUE_FLUSH,null,"quiz")};OutlinedTextField(answer,{answer=it},label={Text("Spell the word")},modifier=Modifier.fillMaxWidth().padding(vertical=18.dp),singleLine=true,colors=OutlinedTextFieldDefaults.colors(focusedTextColor=Cream,unfocusedTextColor=Cream,focusedBorderColor=Gold,unfocusedBorderColor=Cream));GoldButton("Submit"){if(answer.trim().equals(words[index],true))correct++;answer="";if(index==words.lastIndex)done=true else index++}}else{Spacer(Modifier.height(60.dp));Text("Quiz Complete! ⭐",color=Gold,fontSize=30.sp,fontWeight=FontWeight.Bold);Text("$correct / "+words.size,color=Cream,fontSize=44.sp,modifier=Modifier.padding(24.dp));GoldButton("Done",back)}}}
@Composable fun Progress(back:()->Unit){Column(Modifier.fillMaxSize().padding(18.dp).verticalScroll(rememberScrollState())){Header("🌳 My Progress",back);Text("⭐ Words Mastered",color=Gold,fontSize=22.sp,fontWeight=FontWeight.Bold);Text("0 — let's start practicing!",color=Cream,fontSize=18.sp,modifier=Modifier.padding(12.dp));Text("Recent Quiz Scores",color=Gold,fontSize=22.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=24.dp));Text("Your scores will appear here after you take a quiz.",color=Cream,modifier=Modifier.padding(12.dp));Text("Needs More Practice",color=Gold,fontSize=22.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=24.dp));Text("Mistakes will be saved here so you can learn from them.",color=Cream,modifier=Modifier.padding(12.dp))}}
